### ISSUE TITLE
How to define Artifact Uri and which username and passwrod to use

### ISSUE THREAD

**Issue by chigivigi** [kine/navertical_tasks#10]
I am trying to create a build pipeline in azure devops using your extension for my Business Central AL extension. I am having trouble defining artifactUrl while creating a new container. I do not know what  to put into it and it is a required field. I tried using the url for my demo tenant sandbox environment and tried to use http://aka.ms/getbc. Both returned an error when unpacking a zip file.

What do I need to put for a value inside the artifactUrl ?

Also the other part of the problem is I do not know what to put into the username and password fields or which authorization to use. I have a different accounts for working on my azure devops and for my demo tenant sandbox. And I would like to use my primary account with which I use azure devops and from there publish it to my demo tenant sandbox. Which is in a different tenant.

**Comment by kine** [comment]
See https://freddysblog.com/2020/06/25/working-with-artifacts/ for how the new artifact things works (instead the original solution with images...).

All in the build is related to the temporary environment which is created during the pipeline. It is on you which authentication you will use. If NavUserPassword, you need to enter some login and password which will be used. It is not connected with your demo tenant or something...

**Comment by chigivigi** [comment]
Thank you for your quick response.
I have resolved the problem with what you suggested.
