### ISSUE TITLE
can we use NaverticAL to deploy compiled & signed app to D365 Business central cloud sandbox environment.

### ISSUE THREAD

**Issue by chavansachin20** [kine/navertical_tasks#3]
Hi @kine,

We want to publish the app file (signed app) to the cloud sandbox environment with Command prompt, can we use **NaverticAL** to deploy the app to the cloud sandbox environment?

also, I have gone through the link which helps to upload the app to Sandbox, but now searching for a command which can be used from command prompt / PS - [blog - upload-local extensions in sandbox](https://community.dynamics.com/business/f/dynamics-365-business-central-forum/298407/upload-local-extensions-in-sandbox)  

I have already used VS code to publish to my sandbox, but now want to use a command prompt or **PowerShell** to publish my app to the Sandbox environment. 

--------------------------------------------
_VS code_ : 
{
 "version": "0.2.0",
 "configurations": [
        {
 "type": "al",
 "request": "launch",
 "name": "my app",
 "server": "https://businesscentral.dynamics.com/<GUID>/Sandbox",
 "schemaUpdateMode" :  "ForceSync"
        }
    ]
}

Thanks in Advance! 

Regards
Sachin Chavan

Ref : [yammer blog](https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=363394839265280)

**Comment by kine** [comment]
You can use this command:
```
Upload-PerTenantApp -AppId $appid `
                            -AppSecret $appsecret `
                            -Credentials $cred `
                            -Tenant $tenant `
                            -APIUri $apiuri `
                            -AppPath $file.FullName `
                            -Environment $environment `
                            -APIVersion $apiversion `
                            -WaitForResult

```
But first, you need to create new App in the AAD of the target environment to have the appseret and appid. ApiUri is something like 'api/microsoft/automation/v1.0' and apiversion is v2.0.

**Comment by chavansachin20** [comment]
Thanks, @kine for command, now we are working against creating app in AAD, will keep you posted.

**Comment by chavansachin20** [comment]
Hello @kine, 

I have few queries, is this new App in AAD used to authenticate the user who is going to publish the app to the cloud portal? 

Also, I have found a [blog](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-the-application-to-a-role) which helps to create a new App in AAD which requires [Role assignment under Access control (IAM)](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-the-application-to-a-role), please suggest a role which will only publish the BC app to BC tenant.

Thanks :)

**Comment by kine** [comment]
Hi @chavansachin20 ,
Here is my settings of permissions. 
![image](https://user-images.githubusercontent.com/110221/67481890-05bd5480-f663-11e9-9d43-a815b8ceb6b5.png)

**Comment by jordan992** [comment]
Hey
were you able to use azure pipelines to deploy your AL extension to a sandbox business central? 

I would like to use it to deploy to my sandbox and production business central instances.

**Comment by kine** [comment]
Yes, it should work.
