### ISSUE TITLE
Failed : Install NVRAppDevOps and navcontainerhelper PowerShell modules

### ISSUE THREAD

**Issue by chavansachin20** [kine/navertical_tasks#4]
Hi @kine , 

we have installed NaverticAL from DevOps and while running agent we are getting below error 

I think inside Build pipeline, Agent job is not running Powershell as Run as admin.

can you help here to pass this agent job?

**Error details :** 
##[error]Administrator rights are required to install packages in 'C:\Program Files\PackageManagement\ProviderAssemblies'. Log on to the computer with an account that has Administrator rights, and then try again, or install in 'C:\WINDOWS\ServiceProfiles\NetworkService\AppData\Local\PackageManagement\ProviderAssemblies' by adding "-Scope CurrentUser" to your command. You can also try running the Windows PowerShell session with elevated rights (Run as Administrator).

![image](https://user-images.githubusercontent.com/5293496/70034082-a4c85b00-15d6-11ea-8051-1b9e23baed51.png)

Thanks in Advance!

**Comment by kine** [comment]
Hi @chavansachin20 
you need to setup the agent to run as admin. If you set it to run in console, run it as admin after you login. If you set it as service (I never tried this), check that the user under which it is running, is admin.

**Comment by chavansachin20** [comment]
also, we receive an error related to **TestLibraryOnly** parameter while executing "Create container". 

##[error]A parameter cannot be found that matches parameter name 'TestLibraryOnly'.

![image](https://user-images.githubusercontent.com/5293496/70205754-2e009e80-174b-11ea-8641-eeda8d1e6156.png)

**Comment by kine** [comment]
Hi @chavansachin20,
please, keep one issue per one problem. If you have another, open new issue. It will help to track better the progress. I have created new issue for the TestLibraryOnly error.

Can you confirm that the Install or update scripts task is running ok now, when the Agent is running as admin?

**Comment by chavansachin20** [comment]
it still giving me the same message. 

![image](https://user-images.githubusercontent.com/5293496/70226298-9ca72180-1776-11ea-892b-ea412b5d5989.png)


![image](https://user-images.githubusercontent.com/5293496/70226270-8e590580-1776-11ea-8538-320a1cb5d194.png)

**Comment by kine** [comment]
How is your agent running? As service or in console?

**Comment by chavansachin20** [comment]
in console.
![image](https://user-images.githubusercontent.com/5293496/70230915-5904e580-177f-11ea-9947-88f5fe8899aa.png)

**Comment by kine** [comment]
It is not enough, you need to make it run as admin. I am running the agent manually, you can try to check "Run as admin" property on the agent or something.

**Comment by kine** [comment]
See e.g. https://stackoverflow.com/questions/54144386/azure-devops-vsts-start-build-agent-as-an-administrator-interactive-mode-i

**Comment by chavansachin20** [comment]
Thanks, @kine this works for me!
