### ISSUE TITLE
Create container create a container with wrong image

### ISSUE THREAD

**Issue by chavansachin20** [kine/navertical_tasks#6]
Hi @kine ,

I have created a task under my Agent pool, with image Name "**mcr.microsoft.com/businesscentral/sandbox:us**" but container was created with "**mcr.microsoft.com/dynamicsnav:generic-1903**" , see below attachment for reference.

**Screen 1 : Task details**
![image](https://user-images.githubusercontent.com/5293496/70708470-97ab1a80-1d00-11ea-986c-418e57cd53ab.png)

**Screen 2 : Task run details**
![image](https://user-images.githubusercontent.com/5293496/70708512-b4475280-1d00-11ea-8201-dec79fb2abb2.png)

**Comment by chavansachin20** [comment]
**screen 3 : docker container details** 
![image](https://user-images.githubusercontent.com/5293496/70708554-cfb25d80-1d00-11ea-868b-b4873ab0b23f.png)

**Comment by kine** [comment]
Hi @chavansachin20 
that's correct. It is working in this way when the used OS version is not compatible with the specific image. Please, read more about navcontainerhelper... https://blogs.msdn.microsoft.com/freddyk/tag/generic-image/

**Comment by chavansachin20** [comment]
@kine : Can you please recommend which OS tag needs to add under **Create container** to resolve this OS issue.

![image](https://user-images.githubusercontent.com/5293496/70769729-aa6d3000-1d90-11ea-969d-6e37d1899a85.png)

**Comment by kine** [comment]
Question is what is your problem? what you want to solve? the BC running inside the generic image should be the correct one from the image you specified...

**Comment by chavansachin20** [comment]
**Actual**: docker container is created with NAV image 
**Expected**: docker container should be created with BC image

**Comment by kine** [comment]
That's correct and expected behavior.
Do not look at the image name, it is missleading. It is GENERIC image used for NAV AND BC, which have nothing inside by default, but navcontainerhelper scripts will take all what is needed from the selected image you want (NAV or BC, in your case BC). Just read the log when creating such a container, there are things like

```
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying ReportBuilder

```
Those are the lines where the generic image will take the files from the specific image you selected and will use them to run BC/NAV.

**Comment by chavansachin20** [comment]
@kine : if the image name is misleading and this is an expected behavior, then we can close the case.

Thanks 
Sachin Chavan
