### ISSUE TITLE
unable to sign Business Central app - with navertical_tasks "Sign App with certificate through Container"

### ISSUE THREAD

**Issue by chavansachin20** [kine/navertical_tasks#7]
Hi @kine ,

I have created a task which Signs app through container as below: 
![image](https://user-images.githubusercontent.com/5293496/71004155-b269fe80-2107-11ea-812f-6f85ec8401a8.png)

when I execute this task it succeeded but it won't sign the app. 
![image](https://user-images.githubusercontent.com/5293496/71003022-69657a80-2106-11ea-9964-5ba29d7d0ddf.png)

can you please share expected details under the task, like sample example. 

**Actual**: app not signed with task created under build pipeline.
**Expectation**: the app should be signed 

Thanks
Sachin Chavan

**Comment by kine** [comment]
Hi @chavansachin20 ,
1) How do you test that the app is not signed?
2) Could you send me the log for the job?

**Comment by chavansachin20** [comment]
1. App > right Click > Properties > **Digital Signatures** > Signature list 

**Actual**: App > right Click > Properties > **Digital Signatures** tab is not present
**Expected**: App > right Click > Properties > **Digital Signatures** tab should be present with date and time stamp.


2. logs from DevOps > see below screenshot 
![image](https://user-images.githubusercontent.com/5293496/71016397-1b0ea680-211b-11ea-9da6-c305e9f053ff.png)

**Comment by kine** [comment]
It seems that the app was not found. If you have App file = myTest.App without folder, it will search in current folder and subfolders. I am using App file =$(Agent.BuildDirectory)/App/*.app
(App is name of my artifact from the build stage).
If all is ok, the output should be like this (3 app files found):
![image](https://user-images.githubusercontent.com/110221/71060673-65694500-2166-11ea-89db-237774e05862.png)

**Comment by chavansachin20** [comment]
Thanks, @kine ! this worked for me.
