### ISSUE TITLE
[Create Container] ArtifactUrl issue

### ISSUE THREAD

**Issue by judecot** [kine/navertical_tasks#9]
Hi,

I have a problem understanding how this parameter is used to. I thought it was the imageName of the container (as I didn't found this parameter) but it seems to not "want" to download the image I give to him. For example, with this artifactUrl value: **mcr.microsoft.com/businesscentral/sandbox**

I have this error

![image](https://user-images.githubusercontent.com/29598240/84873078-fd4adb80-b082-11ea-8abe-20d6848a3bd4.png)

So in fact, this is a two-questions-issue.

- What is the purpose of ArtifactUrl parameter ?
- How to set correctly the imageName parameter for navcontainerhelper ? 

Thanks for your help

**Comment by kine** [comment]
Hi @JulienDecottignies,
please, do not use this yet, it is preparation for something which is not public yet. I recommend to follow @freddydk twitter or https://freddysblog.com/ for more when it will be available.

**Comment by kine** [comment]
Just to be sure: use the ImageName only and let the ArtifactUrl empty or use prvious version of the task (v3). Same for other functions, id it is not working, use previous version of the task for now.
